### PR TITLE
remove grape-swagger version

### PR DESCRIPTION
**Pull request by tian-xiaobo**
Fix NameError (uninitialized class variable @@hide_format in #Class:0x00000006debf88):
see https://github.com/tim-vandecasteele/grape-swagger/issues/60

### CODE REVIEW

**Comment by dblock** [comment]
Can you please explain this change? It effectively does nothing since we say you need a minimal version, so now it says you need any version.

**Comment by gnapse** [comment]
The problem is that this gem is using grape-swagger 0.7.2, which doesn't support grape 0.10.1. You guys should upgrade to the latest, 0.9.0. See tim-vandecasteele/grape-swagger#60 as @tian-xiaobo pointed out above.

**Comment by dblock** [comment]
@gnapse You're saying that in .gemspec it should say >= 0.9.0, I don't think so because grape-swagger does support older versions of everything, but you're right that *if* you use Grape 0.10.x you need newer versions, including of this gem.

**Comment by gnapse** [comment]
I'm saying that the last released version of the gem as of today ([0.0.10](https://rubygems.org/gems/grape-swagger-rails/versions/0.0.10)) has the following dependency:

```
grape-swagger ~> 0.7.2
```

And with this dependency, the following error occurs:

```
Fix NameError (uninitialized class variable @@hide_format in #Class:0x00000006debf88):
```

That error is caused by the `grape-swagger` gem, but was fixed in more recent versions. However, when using this repo from rubygems the error still occurs because of that dependency stated above.

The funny thing is that this repo's gemspec already has the dependency updated to `>= 0.72` instead of `~> 0.7.2`, but that's only on the master branch, and apparently there has been no new releases since that change. So bottomline is, a new release of this gem would solve the problem. Otherwise, everyone using it should point the Gemfile to github instead of to the standard in rubygems. Instead of this

```ruby
gem 'grape-swagger-rails'
```

We need to put this:

```ruby
gem 'grape-swagger-rails', github: 'BrandyMint/grape-swagger-rails'
```

**Comment by dblock** [comment]
Yes, you're right. This is already fixed in https://github.com/BrandyMint/grape-swagger-rails/pull/41, we need a release, cc @unloved. I had volunteered to do it, haven't heard back :)

**Comment by johnhamelink** [comment]
Please do make this release, this bug is stopping me upgrading to rails 4.2

**Comment by dblock** [comment]
I have been talking to @unloved, we're going to try to move this to https://github.com/TinkerDev/grape-swagger-rails and make a release.

**Comment by dblock** [comment]
Fyi, I released 0.1.0 from https://github.com/TinkerDev/grape-swagger-rails.

**Pull request closed without merging**
